//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public System.Guid HeroID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public string HeroFirstName { get; set; }
        public string HeroLastName { get; set; }
        public string HeroAbility { get; set; }
        public System.DateTime HeroStartTrainingDate { get; set; }
        public int HeroSuitColorsID { get; set; }
        public decimal HeroStartingPower { get; set; }
        public decimal HeroCurrentPower { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
